### PR TITLE
Upgraded to Swift 5

### PR DESCRIPTION
**Pull request by jpauljm**

### CODE REVIEW

**Comment by alephao** [comment]
Hi Jean, thanks for the pull-request!

There are two things I need before I can merge this PR.

- [ ] Update the Xcode version on `.travis.yml`, I guess 10.3 would be fine
- [ ] Update the Example project to Swift 5.0

If you don't have time, let me know and I'll help you

**Comment by alephao** [comment]
Apparently, there is someone else working on the same issue here #9

**Comment by alephao** [comment]
I'm closing this since it was done on #9

**Comment by jpauljm** [comment]
No problem! Thanks!



Jean Paul Marinho (aKANJ)
Senior iOS and Unity Engineer | UnityBR Leader
@aKANJx

**Pull request closed without merging**
