### PR TITLE
Swift update

### PR DESCRIPTION
**Pull request by jessecanderson**
This was to update the project to Swift 5.x. I removed redundant modifiers and deprecated method names in the project. It built and passed all the tests locally.

### CODE REVIEW

**Comment by jessecanderson** [comment]
Trying to figure out what I did wrong. It builds fine in Xcode and all the tests seem to pass so I'm not sure what is causing the "Check Dependencies" error.

**Comment by alephao** [comment]
Hi @jessecanderson, thanks for the pull-request!

There are two things I need before I can merge this PR.

- [x] Update the Xcode version on `.travis.yml`, I guess 10.3 would be fine
- [x] Update the Example project to Swift 5.0

If you don't have time, let me know and I'll help you

**Comment by jessecanderson** [comment]
Got it, thank you! I wasn't aware on the .travis.yml file. It looks like it all builds successfully. Thank you!

**Review by alephao — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
